### ISSUE TITLE
Migrate to ctn-archive

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#106]
@tbekolay would it be possible to move this repo to ctn-archive as it is no longer in use?

**Comment by tbekolay** [comment]
Sounds good! Shall we rename it to avoid confusion also?

**Comment by mundya** [comment]
Might be a good idea, "old_nengo_spinnaker"?

**Comment by tbekolay** [comment]
For the old "nengo_gui" we did "nengo_gui_2014". Would a year make sense for spinnaker too? "old" prefix or suffix is good too!

**Comment by mundya** [comment]
Yeah, _2014 suits me fine

**Comment by tbekolay** [comment]
Done!
