### ISSUE TITLE
Data Classes

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#14]
I noticed today when putting together the Python for multiple filters that the Data classes we have in the Builder (`EnsembleData` etc.) seem to duplicate a lot of the tasks of the Vertex classes (`EnsembleVertex`) that we require for PACMAN integration.  Would it be worth our while combining these objects?  Is there a big reason I'm missing as to why we shouldn't?

When I first started writing a PACMAN front-end for Nengo my intention was to have the Builder build the graph directly, here it feels a bit like we build one graph representation only to go on to build another.

**Comment by tcstewar** [comment]
I could definitely see combining those classes.  I think the fact that they're separate is mostly just an artefact of how we went about writing it the first time...  So I'd be all for merging them.  :)

**Comment by mundya** [comment]
Awesome!
