### ISSUE TITLE
Fixed point neurons

### ISSUE THREAD

**Issue by tcstewar** [ctn-archive/nengo_spinnaker_2014#16]
So, I've now got a good fixed-point neuron model implementation..  I haven't got it integrated into nengo or nengo_spinnaker yet, as we're in the midst of trying out a bunch of options to do that more generally.  This is in https://github.com/ctn-waterloo/neuron_models

That said, as I was working on it I stumbled on a small addition that could be made to the model that might make it perform almost exactly like the floating point version.  The cost of this would be one fixed-point divide per spike.  I don't know how expensive a divide is on SpiNnaker, but with just one per spike it might be doable....

Here's the trick...  let's start with the basic code:

``` python
class LIFFixedPool(NeuronPool):
    def make(self, n_neurons):
        self.voltage = np.zeros(n_neurons, dtype='i32')
        self.refractory_time = np.zeros(n_neurons, dtype='u8')
        self.dt = None

    def step(self, dt, J):
        # initialize some variable, just in case someone changes dt on us
        if self.dt != dt:
            self.dt = dt
            self.dt_over_tau_rc = int(dt * 0x10000 / self.tau_rc)
            self.ref_steps = int(self.tau_ref / dt)

        # convert to fixed point
        J = np.asarray(J * 0x10000, dtype='i32')

        dv = ((J - self.voltage) * self.dt_over_tau_rc) >> 16
        dv[self.refractory_time > 0] = 0
        self.refractory_time[self.refractory_time > 0] -= 1
        self.voltage += dv
        self.voltage[self.voltage < 0] = 0
        spiked = self.voltage > 0x10000
        self.refractory_time[spiked > 0] = self.ref_steps
        self.voltage[spiked > 0] = 0
        return spiked
```

As far as I can tell, that's almost the same math as is happening on SpiNNaker (but in this code I've separated out the encoders, gain and bias -- that all gets taken care of externally and all this code is worried about is dealing with the input current J)

The only difference I see is I'm using dt/tau_rc, rather than 1/tau_rc.  I couldn't find that scaling factor in your code, so I'm not sure if that's something we missed or if it's being taken care of elsewhere (or if it's just part of the units on tau_rc).

In any case, the difference between this model and the ideal LIF neuron is that the refractory period becomes slightly too long.  The spike happens at some point within the time step, but the refractory period lasts until the end of a time step, so refractory periods are always longer than desired.  In the flotaing point implementation, we do some weird logic to compute where we are in that time step, but that increases the memory load and is a bit complex to do in fixed point.

So here's an alternative:

``` python
class LIFFixedPool(NeuronPool):
    def make(self, n_neurons):
        self.voltage = np.zeros(n_neurons, dtype='i32')
        self.refractory_time = np.zeros(n_neurons, dtype='u8')
        self.dt = None
        self.lfsr = 1

    def step(self, dt, J):
        # initialize some variable, just in case someone changes dt on us
        if self.dt != dt:
            self.dt = dt
            self.dt_over_tau_rc = int(dt * 0x10000 / self.tau_rc)
            self.ref_steps = int(self.tau_ref / dt)

        # convert to fixed point
        J = np.asarray(J * 0x10000, dtype='i32')

        dv = ((J - self.voltage) * self.dt_over_tau_rc) >> 16
        dv[self.refractory_time > 0] = 0
        self.refractory_time[self.refractory_time > 0] -= 1
        self.voltage += dv
        self.voltage[self.voltage < 0] = 0
        spiked = self.voltage > 0x10000
        self.refractory_time[spiked > 0] = self.ref_steps

        # randomly adjust the refractory period to account for overshoot
        for i in np.where(spiked > 0)[0]:
            p = ((self.voltage[i] - 0x10000) << 16) / dv[i]
            if self.lfsr < p:
                self.refractory_time[i] -= 1
            self.lfsr = (self.lfsr >> 1) ^ (-(self.lfsr & 0x1) & 0xB400)

        self.voltage[spiked > 0] = 0
        return spiked
```

The trick here is to use a 16-bit LFSR random number generator to sometimes decrease the refractory period.  Getting the exact probability `p` requires the divide, since we need to know when during the time step it spiked.

A script to run this and compare it against other models is here:

https://github.com/ctn-waterloo/neuron_models/blob/master/v1-attributes.py

I'm very surprised at how good this is -- I'm quite tempted to use it elsewhere.  I have no idea if it's suitable or needed for the SpiNNaker backend, but I thought I'd bring it up as a possibility.

**Comment by tbekolay** [comment]
This is super cool!

**Comment by tcstewar** [comment]
> This is super cool!

Thanks!  I'm having fun with the neuron models...  I like how easy the Izhikevich neuron was to implement, and I think I've finally sorted out the Right(TM) way to do rate vs spiking neurons (rate neurons should return their firing rate _per dt_, not per second).  And this fixed point thing turned out to be pretty nice, and it'd be interesting to do some benchmarking....

**Comment by mundya** [comment]
> The only difference I see is I'm using dt/tau_rc, rather than 1/tau_rc. I couldn't find that scaling factor in your code, so I'm not sure if that's something we missed or if it's being taken care of elsewhere (or if it's just part of the units on tau_rc).

I _believe_ we're dealing with that missing dt at the point of writing out the decoders (ensemble_vertex.py:105 in the master branch), but there's nothing to stop us removing it from there and including it in one_over_tau_rc (and I actually rather prefer that).

EDIT: I'm not entirely sure I'm saying anything meaningful here, please disregard.

> This is super cool!

Seconded!  I don't know what the time cost will be but we can run some tests, do you want to branch and include the LFSR in ensemble-update.c and I'll stick a test together when I have some time (probably tomorrow sadly).

**Comment by mundya** [comment]
> but there's nothing to stop us removing it from there and including it in one_over_tau_rc (and I actually rather prefer that).

In fact I liked the change so much that I made it in the refactoring branch 2e6ee56891d92786d2ed56b0278daa01162d9418.

**Comment by spwjr** [comment]
so this fixed-point neuron model implementation basically quantize the total current and membrane potential equation. I think it's difficult to map traditional SNN fixed point network model (All to all weight connection with fixed point resolution)  to Nengo.
From my understanding, in Nengo total current contains spikes-induced current and bias current, where spike induced current is derived by sum(spike activity \* decoders) -> filter ->transform and finally \* gain of post neuron. It has multiple dot and summation process before the neurons calculate equation.  On the other hand, traditional SNN model specifies only one weight parameter between connection. It's difficult to distribute the total word length of weight to several parameters in Nengo (gain, decoder, transform, filter)  I guess for 16bits resolution is fine, but for 8 bits or less there would be significant difference

**Comment by tcstewar** [comment]
Yes, one of the main tricks Nengo uses is that instead of storing the entire giant weight matrix, it just stores much smaller matrices (decoders, transform, and encoders) and multiplies those together as needed.  It also puts the filter after the decoder rather than after the whole weight matrix.  That's just because the filter is a linear operator, so it doesn't matter when we do it, so we may as well do it when there's a smaller number of thing to filter.

However, you're quite right that this assumption relies on reasonably accurate multiplication and so it might be very sensitive to fixed point issues.  I think you're right that 16 bits seems fine but 8 bits might be pushing it.  That said, I'm also pretty sure that this is a side effect of the fact that we're optimizing the decoders for the ideal floating-point case, and then rounding that to get the fixed point value.  If the optimization took into account the fixed-point nature of the representation, then I'm pretty sure we could get it down to 8 bits for the multiplies (although not for the filter).
