### ISSUE TITLE
Probe PassNodes

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#51]
Before calling `remove_passthrough_nodes` connect a new `ProbedNode` to each pass node: this node will have the correct connections from preceding elements.  During the build step replace each `ProbedNode` with a `ValueSinkVertex`.
- [x] Identify probed pass Nodes
- [x] Add new `ProbedNode`
- [x] Replace `ProbedNodes` with a `ValueSinkVertex` in the build step

**Comment by mundya** [comment]
Looks like we'll also need to add a FilterVertex in in some cases as some PassNodes have synapses, meaning probed PassNodes require two filters(!)

**Comment by tcstewar** [comment]
Yuck...   I'm happy for now just simply ignoring one of the two filters and marking that as a TODO....

**Comment by mundya** [comment]
Which would you prefer to ignore (presumably the one on the probe?)  Another solution would be to write a `ValueSinkVertex` with a 2nd order input filter.
