### ISSUE TITLE
Sliced Decoders

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#60]
@tcstewar These take up a lot of space (and time!)  Am I correct in thinking that we should be able to merge them to form a complete decoder and then be picky about where we transmit the packets?

**Comment by mundya** [comment]
So what I think we do is remove elements which are zero from the transformed decoders and build the list of output keys with this information in mind.

I'm becoming a little envious of the things which aren't challenges in Nengo! :wink:

**Comment by tbekolay** [comment]
> I'm becoming a little envious of the things which aren't challenges in Nengo!

But robots! Driving robots in real time will always be a challenge for reference Nengo :smile_cat:

**Comment by mundya** [comment]
> >    I'm becoming a little envious of the things which aren't challenges in Nengo!
> 
> But robots! Driving robots in real time will always be a challenge for reference Nengo :smile_cat:

Yeah, that is cool :grinning:
