### ISSUE TITLE
SpiNNaker Specific Marking

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#8]
I wanted to get a feel for what people's preferred method of denoting SpiNNaker specific attributes may be.  Examples where this may be used include:
- Hinting that a particular Ensemble should be simulated on a given core
- Indicating that a Node is a function of time only
- Indicating that a Node which is a function of time is periodic
- Providing a C-executable for a given Node when running the model on SpiNNaker

It would be nice to retain the syntax used in general code and make it easy to run the same model on both the reference backend and the SpiNNaker backend, so perhaps:

``` python
a = nengo.Node( ... )

if spinnaker:
    nengo_spinnaker.node_with_aplx( a, path_to_aplx )
```

I guess, alternatively:

``` python
if not spinnaker:
    a = nengo.Node( ... )
else:
    a = nengo_spinnaker.Node( ..., aplx = path_to_aplx )
```

**Comment by tcstewar** [comment]
That is an excellent question.  I really don't know what the best approach is here.  We've batted around a few idea but nothing has gelled yet.  So, in a certain sense we're free to do whatever we want, and if it works well we can make that the standard.  :)

My inclination right now is to go with something like this:

``` python
config = nengo_spinnaker.Config()
...
config[a].aplx = path_to_aplx
...
sim = nengo_spinnaker.Simulator(model, config)
```

So the idea here is to create some configuration object that acts as a dictionary, and then use the nodes (or ensembles) as keys into that dictionary, giving you objects that can have things set on them.  This avoid the need for any global variables, and it means that we're not subclassing Node or Ensemble, which would make it harder to write backend-general code.  Also, if backends implement the Config class, they can indicate what propoerties you're allowed to set on them, so this can catch typos easily.  And we should be able to have a fairly generic default Config implementation that different backends could use (customized with whatever properties they want).

The only reason for the dictionary access approach is that that's also what the current plan is for accessing values from probes  (`value = sim.data[a]`).  But other things could work well too.

**Comment by mundya** [comment]
I could cope with that syntax.  It may not hurt to provide some utility functions for common types though? (e.g., sine waves?)

**Comment by tcstewar** [comment]
I'm not sure those are common enough to warrant inclusion.  When we do sine wave inputs, it's always as some sort of example input, just to test how things are going, and I think that's fine to use the external Node for.  We really haven't seen a use case yet for having some set of "common functions" on Nodes, so I'm tempted to not worry about it till it happens....  :)

**Comment by mundya** [comment]
Should I have a play with this?

**Comment by tcstewar** [comment]
I'm taking a stab at this right now, as it's pretty close to what I already did for a neurogrid backend -- should have it posted today.

**Comment by mundya** [comment]
Awesome!

**Comment by tcstewar** [comment]
There's now a `config` branch that shows how to do this.  You can add in more parameters in the nengo_spinnaker/config.py, and we can even do parameter checking and whatnot, if needed.  :)

This does require pulling the most recent version of `nengo`...  I've updated the `build_utils` branch, which still hasn't been merged into `master`.  So you should just have to pull the latest version of build_utils and it's all good.

**Comment by mundya** [comment]
Merged in :)
