### ISSUE TITLE
Routing Keys by an "Object ID"

### ISSUE THREAD

**Issue by mossblaser** [ctn-archive/nengo_spinnaker_2014#88]
Instead of explicitly defining the "x,y,p" parts of routing keys based on the cores involved, use the observation that all things from a given ensemble/value source/sink are routed to the same place and so a single ID will suffice.

Bonuses of this include:
- Makes optimising spinnaker routing table/filter routing table use trivial
- For all but the scariest models means more bits in the routing key are available for dimension (could be set dynamically allowing the trade-off to be made by end users, possibly even transparently).
- For I/O purposes may allow e.g. a specific bit to be fixed to indicate "packets which should be grabbed for I/O"

**Comment by mundya** [comment]
I like this idea so much I can't quite remember why we're using x, y, p... other than that for a while it looked like PACMAN would enforce this.

The keyspaces stuff should make this dead easy to try out - even with dynamically resizing the fields :smile:

**Comment by mundya** [comment]
This is now done by object ID and partition ID.
