### ISSUE TITLE
Tx->PC message protocol options

### ISSUE THREAD

**Issue by tcstewar** [ctn-archive/nengo_spinnaker_2014#9]
While implementing the tx system (sending data from SpiNNaker to the host),  I'm noting that there's a lot of overhead in the generation of the UDP packet.  Right now, we do a separate packet per dimension, meaning that we get one packet per dimension per millisecond.  This is just a direct echo of the multicast packet itself -- the only payload is the 32-bit key and the 32-bit value, but it bets turned into a pretty large packet.

So I'm wondering whether it might make more sense to have one SDP send occur for the whole vector, so it's just one message per millisecond.  The core would be in charge of gathering the multicast packets it received into a buffer (exactly the same as how the ensembles gather their values), and then every millisecond a separate timer just packages that up as an SDP and sends it.

Thoughts?

**Comment by mundya** [comment]
I did some thinking about this and I'm converging on assigning a given number of dimensions (< 64) to a Tx element, performing an input step rather like on the Ensembles, and transmitting one SDP packet per timestep.  This has the advantage of limiting the fan-in of each Tx element.  The host then needs to look up which dimensions are associated with which incoming SDP packets.

Another option, which I'm favouring less, is to send 32 key/value combinations in each SDP packet.  The Tx will then wait until receiving sufficient MC packets before sending a packet.  This feels like it could stress the comms fabric near this element.

**Comment by tcstewar** [comment]
> I did some thinking about this and I'm converging on assigning a given number of dimensions (< 64) to a Tx element, performing an input step rather like on the Ensembles, and transmitting one SDP packet per timestep. This has the advantage of limiting the fan-in of each Tx element. The host then needs to look up which dimensions are associated with which incoming SDP packets.

I think I like that approach.  In fact, we might even consider going back to one Tx element per Node, since if we're just generating one packet per time step regardless of dimension, it doesn't seem like it's worth the organizational overhead of having of Tx element handle multiple Nodes.   Not sure how I feel about that idea...

**Comment by mundya** [comment]
> In fact, we might even consider going back to one Tx element per Node, since if we're just generating one packet per time step regardless of dimension, it doesn't seem like it's worth the organizational overhead of having of Tx element handle multiple Nodes.

I have no figures, but I'd rather have the organisational overhead than lots of SDP packets... I think.

EDIT: I guess we can start with one Tx per node and see how it goes.  I'd definitely like to consolidate multiple Nodes into one Rx component however.

**Comment by tcstewar** [comment]
> I have no figures, but I'd rather have the organisational overhead than lots of SDP packets... I think.
> 
> EDIT: I guess we can start with one Tx per node and see how it goes. I'd definitely like to consolidate multiple Nodes into one Rx component however.

Yeah, I can see going either way on that.  One thing to keep in mind is that we tend not to have very many inputs and outputs...  Spaun has exactly one input (the visual data, a 784-dimensional vector).  So I'm not sure what the right way to go is.  

Still, it sounds like we'll always have something other than a 1-to-1 mapping between Nodes and Rx or Tx, so it might make sense to just stick with what we have now (a single Tx and a single Rx).

Anyway, I'll finish up getting the current Tx approach working, and then maybe fiddle with the alternate approach(es).

**Comment by mundya** [comment]
>  we tend not to have very many inputs and outputs...

But we also want to support people who are learning/messing with Nengo who may have larger IO requirements...

>  a 784-dimensional vector

:worried:  We are breaking that down right?

> Still, it sounds like we'll always have something other than a 1-to-1 mapping between Nodes and Rx or Tx, so it might make sense to just stick with what we have now (a single Tx and a single Rx).

In this case I'd far rather make it explicit that a Tx/Rx element only supports a given number of dimensions and ensure that we handle that (i.e., when we add these elements we keep a track of their dimensional fan-in/out and add additional ones as necessary).

**Comment by tcstewar** [comment]
> In this case I'd far rather make it explicit that a Tx/Rx element only supports a given number of dimensions and ensure that we handle that (i.e., when we add these elements we keep a track of their dimensional fan-in/out and add additional ones as necessary).

That makes sense to me...

**Comment by mundya** [comment]
I've also just realised that some (hopefully soon to come) changes to PACMAN will save us from having to explicitly handle the splitting of Tx and Rx components, so when we construct the graph representation we will still have the ideal case of one Tx and one Rx.
